title: Biological Expression Language
description: >
  Encoding biomedical knowledge in a computable form

google_analytics: UA-166029785-2

github_username:  biological-expression-language
linkedin_username: 4257384

theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
